spring:
    #  profiles:
    #    active: lcoal
    config:
        activate:
            on-profile:
                - dev
#    thymeleaf:
#        cache: false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/schedulework?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: ljm19991115
        ##连接池
        hikari:
            pool-name: PoolConnectPool
server:
    port: 9001
mybatis:
    ##mapper.xml存放位置
    mapper-locations: classpath*:/mapper/*.xml
    type-aliases-package: com.schedulework.login.Entity
    #config-location: classpath:mybatis/mybatis-config.xml
oauth2:
    github:
        userInfoUrl: https://api.github.com/user




